//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHostService1")]
    public interface IHostService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostService1/GetRowById", ReplyAction="http://tempuri.org/IHostService1/GetRowByIdResponse")]
        HostService.GetShortInfo GetRowById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostService1/GetRowById", ReplyAction="http://tempuri.org/IHostService1/GetRowByIdResponse")]
        System.Threading.Tasks.Task<HostService.GetShortInfo> GetRowByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostService1/FindByLastName", ReplyAction="http://tempuri.org/IHostService1/FindByLastNameResponse")]
        HostService.GetShortInfo[] FindByLastName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHostService1/FindByLastName", ReplyAction="http://tempuri.org/IHostService1/FindByLastNameResponse")]
        System.Threading.Tasks.Task<HostService.GetShortInfo[]> FindByLastNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHostService1Channel : WebClient.ServiceReference1.IHostService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HostService1Client : System.ServiceModel.ClientBase<WebClient.ServiceReference1.IHostService1>, WebClient.ServiceReference1.IHostService1 {
        
        public HostService1Client() {
        }
        
        public HostService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HostService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HostService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HostService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HostService.GetShortInfo GetRowById(int id) {
            return base.Channel.GetRowById(id);
        }
        
        public System.Threading.Tasks.Task<HostService.GetShortInfo> GetRowByIdAsync(int id) {
            return base.Channel.GetRowByIdAsync(id);
        }
        
        public HostService.GetShortInfo[] FindByLastName(string name) {
            return base.Channel.FindByLastName(name);
        }
        
        public System.Threading.Tasks.Task<HostService.GetShortInfo[]> FindByLastNameAsync(string name) {
            return base.Channel.FindByLastNameAsync(name);
        }
    }
}
